#!/bin/bash

# Arch Linux 急救脚本
# @wwxiaoqi

echo "Reflector disabled"
systemctl stop reflector.service
systemctl status reflector.service

echo "Replace the mirror source"
# 外国语大学镜像站
echo "Server = https://mirrors.bfsu.edu.cn/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
# 兰州大学开源镜像站
echo "Server = https://mirror.lzu.edu.cn/archlinux/\$repo/os/\$arch" >> /etc/pacman.d/mirrorlist
# 华为开源镜像站
echo "Server = https://repo.huaweicloud.com/archlinux/\$repo/os/\$arch" >> /etc/pacman.d/mirrorlist
# 清华大学开源软件镜像站
echo "Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/\$repo/os/\$arch" >> /etc/pacman.d/mirrorlist
# 中国科学技术大学开源镜像站
echo "Server = https://mirrors.ustc.edu.cn/archlinux/\$repo/os/\$arch" >> /etc/pacman.d/mirrorlist

# 可以使用以下命令替换文件中的 nvme0n1p 字符串
# 在 vim 中可以直接使用 /s/nvme0n1p/sda/g
# sed -i "s/nvme0n1p/sda/g" file
echo "Mount directory"
mount -t btrfs -o subvol=/@,compress=zstd /dev/nvme0n1p3 /mnt
mkdir /mnt/home
mount -t btrfs -o subvol=/@home,compress=zstd /dev/nvme0n1p3 /mnt/home
mkdir -p /mnt/boot/efi
mount /dev/nvme0n1p1 /mnt/boot/efi
swapon /dev/nvme0n1p2
